// Single source of truth for the demo dataset.
// Consumed by `server/seed.js` (SQLite seeding) and by the Vercel serverless
// functions in `api/` (stateless read-only endpoints), so both always serve
// the same data. Every row is clearly labelled demo data (is_demo) in the UI.
export const DEPARTMENTS = [
  ['Deputy Commissioner (DC) Office', 'DC'],
  ['Revenue Department', 'Revenue'],
  ['Education (S) Department', 'Education'],
  ['Health & Family Welfare Department', 'Health'],
  ['Agriculture Department', 'Agriculture'],
  ['Transport Department', 'Transport'],
  ['Social Welfare Department', 'DSWO'],
  ['Municipal Administration, Housing & Urban Development (MAHUD)', 'MAHUD'],
  ['Public Health Engineering Department (PHED)', 'PHED'],
  ['Public Works Department (PWD)', 'PWD'],
  ['Electricity Department (MSPDCL)', 'MSPDCL'],
  ['Manipur Police', 'Police'],
];

export const SERVICES = [
  {
    slug: 'income-certificate', name: 'Income Certificate', category: 'Certificates', dept: 'Deputy Commissioner (DC) Office',
    description: 'An official certificate stating your annual family income, required for scholarships, fee concessions, subsidised schemes and job reservations.',
    eligibility: 'Any resident of Manipur who can provide proof of family income. Applicant should hold a valid residence proof of the state.',
    documents: [
      { item: 'Identity proof (Aadhaar / Voter ID)', note: 'Any one government-issued photo ID' },
      { item: 'Address proof (utility bill / residence certificate)', note: 'Confirms you live in Manipur' },
      { item: 'Income-related document (salary slip / self-declaration)', note: 'Salary slips if employed; signed affidavit if self-employed' },
      { item: 'Passport-size photograph', note: '1 recent photo' },
    ],
    steps: [
      'Collect the income certificate application form from the DC office or download it from the district portal.',
      'Fill in the form and attach all required documents.',
      'Submit at the DC/SDC office counter and pay the nominal fee.',
      'Collect the acknowledgement slip; the certificate is usually issued within 7–15 working days.',
    ],
    link: null,
    keywords: ['income', 'certificate', 'salary', 'earning', 'scholarship', 'obc', 'ewse', 'financial'],
  },
  {
    slug: 'residence-certificate', name: 'Residence Certificate', category: 'Certificates', dept: 'Deputy Commissioner (DC) Office',
    description: 'Proof that you are a resident of Manipur, needed for admission, jobs, certificates and state schemes.',
    eligibility: 'Applicant must have resided in Manipur for at least the minimum period specified by the district administration.',
    documents: [
      { item: 'Identity proof (Aadhaar / Voter ID)', note: 'Any one' },
      { item: 'Land document or rent agreement', note: 'Proof of staying in the state' },
      { item: 'Passport-size photograph', note: '1 recent photo' },
    ],
    steps: ['Get the application form from the DC/SDC office.', 'Attach residence proof documents.', 'Submit and collect acknowledgement.', 'Certificate issued after local verification.'],
    link: null,
    keywords: ['residence', 'domicile', 'certificate', 'address', 'resident'],
  },
  {
    slug: 'caste-certificate', name: 'Caste Certificate (ST / SC / OBC)', category: 'Certificates', dept: 'Deputy Commissioner (DC) Office',
    description: 'Certifies membership of a Scheduled Tribe, Scheduled Caste or Other Backward Class, used for reservations in education, jobs and schemes.',
    eligibility: 'Applicant or their family must belong to a recognised ST/SC/OBC community of Manipur.',
    documents: [
      { item: 'Community/tribe proof of parent or relative', note: 'Old caste certificate of a family member helps' },
      { item: 'Identity proof', note: 'Aadhaar or Voter ID' },
      { item: 'Residence proof', note: 'Confirms residency in Manipur' },
    ],
    steps: ['Obtain the caste certificate form from the DC office.', 'Attach community proof and ID documents.', 'Submit for verification by the district authority.', 'Collect the certificate after verification.'],
    link: null,
    keywords: ['caste', 'st', 'sc', 'obc', 'tribe', 'certificate', 'reservation', 'scheduled'],
  },
  {
    slug: 'birth-certificate', name: 'Birth Certificate', category: 'Certificates', dept: 'Municipal Administration, Housing & Urban Development (MAHUD)',
    description: 'The first legal identity document of a child, issued by the registrar of births and deaths; needed for school admission and future documents.',
    eligibility: 'Birth must be registered within 21 days at the municipal council / gram panchayat where the child was born.',
    documents: [
      { item: 'Hospital birth record / discharge summary', note: 'Issued by the hospital or ANM' },
      { item: 'Parents\' identity proof', note: 'Aadhaar of either parent' },
      { item: 'Marriage certificate of parents (optional)', note: 'Helps avoid queries' },
    ],
    steps: ['Register the birth at the municipal office within 21 days.', 'Submit hospital record and parents\' ID.', 'Receive the registration slip.', 'Collect the printed birth certificate.'],
    link: 'https://crsorgi.gov.in',
    keywords: ['birth', 'certificate', 'newborn', 'child', 'crs'],
  },
  {
    slug: 'death-certificate', name: 'Death Certificate', category: 'Certificates', dept: 'Municipal Administration, Housing & Urban Development (MAHUD)',
    description: 'Legal proof of death, required for pension transfer, property mutation, insurance and bank claims.',
    eligibility: 'Death should be registered within 21 days at the municipal office or panchayat where the death occurred.',
    documents: [
      { item: 'Hospital death record / cremation slip', note: 'From the hospital or crematorium' },
      { item: 'Deceased\'s identity proof', note: 'Aadhaar or Voter ID' },
      { item: 'Applicant\'s identity proof', note: 'Person applying for the certificate' },
    ],
    steps: ['Register the death at the municipal office.', 'Attach hospital/cremation record.', 'Collect the registration slip.', 'Collect the death certificate.'],
    link: 'https://crsorgi.gov.in',
    keywords: ['death', 'certificate', 'cremation', 'legal heir'],
  },
  {
    slug: 'driving-licence', name: 'Driving Licence (DL)', category: 'Transport', dept: 'Transport Department',
    description: 'Official licence to drive a motor vehicle, issued after learning licence and driving test.',
    eligibility: '18+ for light motor vehicles; 16+ with guardian consent for gearless two-wheelers. Must hold a learner\'s licence first.',
    documents: [
      { item: 'Learner\'s licence', note: 'At least 30 days old' },
      { item: 'Identity proof (Aadhaar)', note: 'Mandatory' },
      { item: 'Address proof', note: 'Any one' },
      { item: 'Passport-size photographs', note: '2 recent photos' },
      { item: 'Form 1A medical certificate (40+ applicants)', note: 'Signed by a registered doctor' },
    ],
    steps: [
      'Apply for a learner\'s licence on the Parivahan portal and pass the online test.',
      'After 30 days, book a driving test slot for the permanent licence.',
      'Appear for the practical driving test at the RTO.',
      'DL is dispatched to your registered address after passing.',
    ],
    link: 'https://sarathi.parivahan.gov.in',
    keywords: ['driving', 'licence', 'license', 'dl', 'vehicle', 'rto', 'parivahan', 'car', 'bike'],
  },
  {
    slug: 'vehicle-registration', name: 'Vehicle Registration (RC)', category: 'Transport', dept: 'Transport Department',
    description: 'Register a new or transferred vehicle to get the Registration Certificate (RC book).',
    eligibility: 'Vehicle purchased within the state; dealer or owner applies within 30 days of purchase.',
    documents: [
      { item: 'Form 20 (registration application)', note: 'Available at RTO or dealer' },
      { item: 'Sales invoice of the vehicle', note: 'From the dealer' },
      { item: 'Insurance certificate', note: 'Valid motor insurance' },
      { item: 'PUC certificate', note: 'Pollution-under-control' },
      { item: 'Address & identity proof', note: 'Aadhaar preferred' },
    ],
    steps: ['Submit Form 20 with documents at the RTO.', 'Pay registration fee and road tax.', 'Vehicle physical inspection.', 'RC book issued and dispatched.'],
    link: 'https://vahan.parivahan.gov.in',
    keywords: ['vehicle', 'rc', 'registration', 'vahan', 'car', 'bike'],
  },
  {
    slug: 'post-matric-scholarship-st', name: 'Post-Matric Scholarship for ST Students', category: 'Education', dept: 'Education (S) Department',
    description: 'Tuition and maintenance allowance for Scheduled Tribe students studying in classes 11 and above, up to post-graduation.',
    eligibility: 'ST students of Manipur with family income up to ₹2.5 lakh per year, enrolled in a recognised institution.',
    documents: [
      { item: 'Caste certificate (ST)', note: 'Issued by DC office' },
      { item: 'Income certificate', note: 'Family income proof' },
      { item: 'Previous marksheet', note: 'Last passed exam' },
      { item: 'Institute bona fide certificate', note: 'From your college/school' },
      { item: 'Bank account details (student\'s own)', note: 'For direct benefit transfer' },
    ],
    steps: [
      'Register on the National Scholarship Portal (NSP).',
      'Fill the Post-Matric ST scholarship application online.',
      'Upload documents and submit to the institute for verification.',
      'Scholarship is credited directly to the bank account after approval.',
    ],
    link: 'https://scholarships.gov.in',
    keywords: ['scholarship', 'st', 'student', 'education', 'post-matric', 'nsp', 'college'],
  },
  {
    slug: 'pre-matric-scholarship', name: 'Pre-Matric Scholarship (Class 9–10)', category: 'Education', dept: 'Education (S) Department',
    description: 'Financial support for school students of classes 9 and 10 from disadvantaged communities to reduce dropouts.',
    eligibility: 'Students of classes 9–10 in recognised schools; income limits apply as notified each year.',
    documents: [
      { item: 'Caste/community certificate (if applicable)', note: 'For reserved categories' },
      { item: 'Income certificate', note: 'Family income proof' },
      { item: 'Previous class marksheet', note: 'From school' },
      { item: 'Bank account details', note: 'Student or parent\'s account' },
    ],
    steps: ['Apply through the school or National Scholarship Portal.', 'Attach required documents.', 'School verifies the application.', 'Scholarship credited after approval.'],
    link: 'https://scholarships.gov.in',
    keywords: ['scholarship', 'school', 'student', 'pre-matric', 'class 9', 'class 10'],
  },
  {
    slug: 'cmht-health-cover', name: 'CMHT — Chief Minister-gi Hakshelgi Tengbang (Health Cover)', category: 'Health', dept: 'Health & Family Welfare Department',
    description: 'State health assurance scheme providing cashless treatment cover at empanelled hospitals for eligible poor families of Manipur.',
    eligibility: 'Families listed in the state socio-economic data with verified income criteria; enrollment through the CMHT cell.',
    documents: [
      { item: 'Aadhaar card of family members', note: 'Mandatory for enrollment' },
      { item: 'Ration card', note: 'Household proof' },
      { item: 'Income certificate', note: 'For eligibility verification' },
    ],
    steps: ['Check family eligibility at the CMHT cell of your district hospital.', 'Submit enrollment documents.', 'Receive the CMHT card.', 'Use the card for cashless treatment at empanelled hospitals.'],
    link: null,
    keywords: ['health', 'insurance', 'cmht', 'hospital', 'treatment', 'medical', 'cashless'],
  },
  {
    slug: 'ayushman-bharat-pmjay', name: 'Ayushman Bharat — PM-JAY', category: 'Health', dept: 'Health & Family Welfare Department',
    description: 'National health cover of ₹5 lakh per family per year for secondary and tertiary hospitalisation at empanelled hospitals.',
    eligibility: 'Families identified as deprived per the Socio-Economic Caste Census (SECC) criteria.',
    documents: [
      { item: 'Aadhaar card', note: 'For identity and e-KYC' },
      { item: 'Ration card / SECC listing', note: 'Household identification' },
      { item: 'Mobile number', note: 'For OTP verification' },
    ],
    steps: ['Check family eligibility at an Ayushman Arogya Mandir or on the PM-JAY portal.', 'Complete e-KYC with Aadhaar.', 'Receive the Ayushman card.', 'Avail cashless treatment at empanelled hospitals.'],
    link: 'https://pmjay.gov.in',
    keywords: ['health', 'pmjay', 'ayushman', 'hospital', 'insurance', 'medical'],
  },
  {
    slug: 'pm-kisan', name: 'PM-KISAN Income Support', category: 'Agriculture', dept: 'Agriculture Department',
    description: '₹6,000 per year paid in three instalments to landholding farmer families for agricultural inputs.',
    eligibility: 'All landholding farmer families with cultivable land; certain exclusions apply (income-tax payers, institutional landholders).',
    documents: [
      { item: 'Aadhaar card', note: 'Mandatory' },
      { item: 'Land record (patta / khasra)', note: 'In applicant\'s name' },
      { item: 'Bank account details', note: 'Aadhaar-linked preferred' },
    ],
    steps: ['Register on the PM-KISAN portal through the local agriculture office (CSC).', 'Land and Aadhaar details are verified.', 'Application is approved by the state department.', 'Instalments credited directly to the bank account.'],
    link: 'https://pmkisan.gov.in',
    keywords: ['farmer', 'agriculture', 'kisan', 'income support', 'subsidy', 'farming'],
  },
  {
    slug: 'kisan-credit-card', name: 'Kisan Credit Card (KCC)', category: 'Agriculture', dept: 'Agriculture Department',
    description: 'Short-term crop loans at subsidised interest rates through banks, repayable after harvest.',
    eligibility: 'Farmers (owners, tenants, sharecroppers) cultivating land or involved in allied activities like fisheries/animal husbandry.',
    documents: [
      { item: 'Land documents', note: 'Patta or tenancy proof' },
      { item: 'Identity proof (Aadhaar)', note: 'Mandatory' },
      { item: 'Crop plan', note: 'Crops you intend to grow' },
      { item: 'Passport-size photograph', note: '1 recent photo' },
    ],
    steps: ['Visit the nearest bank branch or apply via the CSC.', 'Fill the KCC application with crop details.', 'Bank verifies land documents.', 'Credit card issued with sanctioned limit.'],
    link: null,
    keywords: ['farmer', 'loan', 'credit', 'kcc', 'crop', 'agriculture'],
  },
  {
    slug: 'mgnrega-job-card', name: 'MGNREGA Job Card', category: 'Employment', dept: 'Rural Development (via DC Office)',
    description: 'Guaranteed 100 days of paid wage employment per rural household per year on public works.',
    eligibility: 'Adult members of rural households willing to do unskilled manual work.',
    documents: [
      { item: 'Aadhaar card of applicants', note: 'All adult members' },
      { item: 'Residence proof', note: 'Rural household in Manipur' },
      { item: 'Bank/post office account details', note: 'For wage payment' },
    ],
    steps: ['Apply for a job card at the Gram Panchayat / Block office.', 'Household details are verified and job card issued.', 'Submit a written work demand to the Panchayat.', 'Work is allotted within 15 days of demand; wages paid digitally.'],
    link: 'https://nrega.nic.in',
    keywords: ['job', 'employment', 'nrega', 'mgnrega', 'rural', 'work', 'wages'],
  },
  {
    slug: 'employment-exchange', name: 'Employment Exchange Registration', category: 'Employment', dept: 'Labour & Employment Department',
    description: 'Register as a job-seeker with the district employment exchange to get notified about government vacancies and job fairs.',
    eligibility: 'Residents of Manipur aged 14 and above seeking employment.',
    documents: [
      { item: 'Identity proof (Aadhaar)', note: 'Mandatory' },
      { item: 'Educational qualification certificates', note: 'Marksheets and certificates' },
      { item: 'Passport-size photograph', note: '2 recent photos' },
    ],
    steps: ['Visit the district employment exchange with documents.', 'Fill the registration form.', 'Receive the registration card.', 'Renew registration periodically to stay active.'],
    link: null,
    keywords: ['job', 'employment', 'exchange', 'unemployed', 'vacancy', 'recruitment'],
  },
  {
    slug: 'udyam-registration', name: 'Udyam Registration (MSME)', category: 'Business', dept: 'Ministry of MSME (via DC Office / DIC)',
    description: 'Free online registration for micro, small and medium enterprises to access subsidies, loans and preference in government procurement.',
    eligibility: 'Any proprietorship, partnership, company or SHG running a manufacturing or service enterprise.',
    documents: [
      { item: 'Aadhaar card of the owner/partners', note: 'Mandatory for Udyam' },
      { item: 'PAN of the enterprise (if available)', note: 'For companies/firms' },
      { item: 'Bank account details', note: 'Business account preferred' },
      { item: 'Business address proof', note: 'Electricity bill / rent agreement' },
    ],
    steps: ['Open the Udyam registration portal.', 'Enter Aadhaar and enterprise details.', 'Verify with OTP and classify the business (manufacturing/service).', 'Receive the Udyam Registration Number instantly — it is completely free.'],
    link: 'https://udyamregistration.gov.in',
    keywords: ['business', 'msme', 'udyam', 'enterprise', 'shop', 'registration', 'startup'],
  },
  {
    slug: 'old-age-pension', name: 'Old Age Pension (NSAP)', category: 'Social Welfare', dept: 'Social Welfare Department',
    description: 'Monthly pension for senior citizens (60+) from Below Poverty Line households under the National Social Assistance Programme.',
    eligibility: 'Applicants aged 60+ from BPL/eligible households; higher amount for 80+.',
    documents: [
      { item: 'Age proof (Aadhaar / birth certificate)', note: 'Must show age 60+' },
      { item: 'BPL / income certificate', note: 'Household eligibility' },
      { item: 'Bank account details', note: 'Pension is credited monthly' },
      { item: 'Passport-size photograph', note: '1 recent photo' },
    ],
    steps: ['Collect the pension form from the Social Welfare office (DSWO).', 'Attach age and BPL documents.', 'Verification by the field officer.', 'Pension starts after sanction and is credited monthly.'],
    link: null,
    keywords: ['pension', 'old age', 'senior citizen', 'elderly', 'nsap', 'bpl'],
  },
  {
    slug: 'widow-pension', name: 'Widow Pension (NSAP)', category: 'Social Welfare', dept: 'Social Welfare Department',
    description: 'Monthly pension for widows from eligible poor households to support basic living expenses.',
    eligibility: 'Widows aged 18+ from BPL/eligible households; not remarried.',
    documents: [
      { item: 'Death certificate of husband', note: 'Mandatory' },
      { item: 'Identity proof (Aadhaar)', note: 'Mandatory' },
      { item: 'BPL / income certificate', note: 'Household eligibility' },
      { item: 'Bank account details', note: 'For monthly credit' },
    ],
    steps: ['Collect the form from the DSWO office.', 'Attach death certificate and ID.', 'Field verification.', 'Pension sanctioned and credited monthly.'],
    link: null,
    keywords: ['pension', 'widow', 'nsap', 'social welfare'],
  },
  {
    slug: 'ration-card', name: 'Ration Card (NFSA)', category: 'Social Welfare', dept: 'Consumer Affairs, Food & Civil Supplies',
    description: 'Entitles households to subsidised food grains through the Public Distribution System under the National Food Security Act.',
    eligibility: 'Households meeting NFSA eligibility as identified by the state; new applications via the district food office.',
    documents: [
      { item: 'Aadhaar cards of all family members', note: 'For seeding' },
      { item: 'Residence proof', note: 'Confirms household in Manipur' },
      { item: 'Income declaration', note: 'Self-declaration form' },
    ],
    steps: ['Collect the NFSA application form from the district food office.', 'Attach Aadhaar copies of all members.', 'Verification of household details.', 'Ration card issued; collect from the office or download e-rc.'],
    link: null,
    keywords: ['ration', 'card', 'food', 'nfsa', 'pds', 'subsidy', 'grain'],
  },
  {
    slug: 'land-records-louchapathap', name: 'Land Records (Patta / Jamabandi)', category: 'Land & Revenue', dept: 'Revenue Department',
    description: 'Access and update land ownership records (patta, jamabandi) and apply for certified copies of land documents.',
    eligibility: 'Landowners or interested parties with land details (dag/patta number) in Manipur.',
    documents: [
      { item: 'Existing land document (old patta / deed)', note: 'Any previous record' },
      { item: 'Identity proof (Aadhaar)', note: 'Mandatory' },
      { item: 'Land tax receipt', note: 'Latest payment proof' },
    ],
    steps: ['Visit the Circle Office (SC/SDC Revenue) with land details.', 'Apply for a certified copy or correction.', 'Revenue officials verify the record.', 'Certified copy issued after verification.'],
    link: null,
    keywords: ['land', 'patta', 'jamabandi', 'louchapathap', 'revenue', 'mutation', 'property'],
  },
  {
    slug: 'water-connection', name: 'New Water Connection (PHED)', category: 'Civic Services', dept: 'Public Health Engineering Department (PHED)',
    description: 'Apply for a new household piped water connection under the Functional Household Tap Water scheme.',
    eligibility: 'Households within PHED scheme areas of Manipur.',
    documents: [
      { item: 'Identity proof (Aadhaar)', note: 'Owner\'s ID' },
      { item: 'House ownership proof', note: 'Land document or electricity bill' },
      { item: 'Passport-size photograph', note: '1 recent photo' },
    ],
    steps: ['Apply at the PHED subdivision office or through the scheme\'s village committee.', 'Pay the connection fee.', 'Pipeline inspection by PHED staff.', 'Connection provided and meter installed where applicable.'],
    link: null,
    keywords: ['water', 'connection', 'phed', 'tap', 'supply', 'pipeline'],
  },
  {
    slug: 'streetlight-repair', name: 'Streetlight Repair Request', category: 'Civic Services', dept: 'Electricity Department (MSPDCL)',
    description: 'Report faulty or non-functioning streetlights to the electricity board for repair.',
    eligibility: 'Any resident; you can also report through this platform\'s "Report a Problem" section.',
    documents: [
      { item: 'Location details of the faulty light', note: 'Street/landmark name' },
      { item: 'Photo of the fault (optional)', note: 'Helps faster repair' },
    ],
    steps: ['Note the exact location of the faulty streetlight.', 'Submit the details via "Report a Problem" or call the MSPDCL office.', 'Complaint is assigned to the line section.', 'Repair completed and status updated.'],
    link: null,
    keywords: ['streetlight', 'light', 'electricity', 'repair', 'mspdc', 'pole'],
  },
];

export const SCHEMES = [
  {
    slug: 'post-matric-st-scholarship', name: 'Post-Matric Scholarship for ST Students', dept: 'Education (S) Department',
    benefits: 'Full tuition reimbursement plus monthly maintenance allowance (₹230–₹1,200/month depending on course and hostel status).',
    eligibility: 'ST students of Manipur studying in class 11 or above in recognised institutions; annual family income up to ₹2.5 lakh.',
    documents: ['ST caste certificate', 'Income certificate', 'Previous marksheet', 'Bonafide certificate from institute', 'Student bank account'],
    process: 'Apply online on the National Scholarship Portal, submit to your institute for verification, then state-level approval releases the scholarship by DBT.',
    link: 'https://scholarships.gov.in',
    min_age: 15, max_age: 40, occupations: ['student'], area: 'any', max_income: 250000,
    keywords: ['scholarship', 'student', 'st', 'education', 'college', 'tuition'],
  },
  {
    slug: 'pre-matric-scholarship-minorities', name: 'Pre-Matric Scholarship for Students (Class 9–10)', dept: 'Education (S) Department',
    benefits: '₹100–₹500 per month plus book and ad-hoc grants to help students continue schooling.',
    eligibility: 'Students of classes 9–10 from eligible households; income limits as notified yearly.',
    documents: ['Income certificate', 'Previous marksheet', 'Bonafide certificate', 'Bank account details'],
    process: 'Apply through your school or the National Scholarship Portal; school verifies; scholarship credited by DBT.',
    link: 'https://scholarships.gov.in',
    min_age: 13, max_age: 18, occupations: ['student'], area: 'any', max_income: 350000,
    keywords: ['scholarship', 'student', 'school', 'class 9', 'class 10', 'education'],
  },
  {
    slug: 'cmht-health', name: 'CMHT Health Cover (Chief Minister-gi Hakshelgi Tengbang)', dept: 'Health & Family Welfare Department',
    benefits: 'Cashless treatment up to cover limits at empanelled hospitals across Manipur.',
    eligibility: 'Poor and vulnerable families of Manipur identified through the CMHT verification process.',
    documents: ['Aadhaar card of family members', 'Ration card', 'Income certificate'],
    process: 'Enroll at the CMHT cell of your district hospital; verification followed by card issue.',
    link: null,
    min_age: null, max_age: null, occupations: ['any'], area: 'any', max_income: 200000,
    keywords: ['health', 'cmht', 'medical', 'hospital', 'insurance', 'treatment'],
  },
  {
    slug: 'pm-kisan-scheme', name: 'PM-KISAN (Farmer Income Support)', dept: 'Agriculture Department',
    benefits: '₹6,000 per year in three equal instalments directly to the farmer\'s bank account.',
    eligibility: 'Landholding farmer families; excluded: income-tax payers, institutional landholders, pension holders above ₹10,000/month.',
    documents: ['Aadhaar card', 'Land records (patta)', 'Bank account details'],
    process: 'Register at the agriculture office or CSC; verification by the state; instalments credited by DBT.',
    link: 'https://pmkisan.gov.in',
    min_age: 18, max_age: null, occupations: ['farmer'], area: 'any', max_income: null,
    keywords: ['farmer', 'agriculture', 'kisan', 'income', 'subsidy', 'farming'],
  },
  {
    slug: 'pm-awas-gramin', name: 'PM Awas Yojana — Gramin (Rural Housing)', dept: 'Rural Development (via DC Office)',
    benefits: 'Assistance of ₹1.2–1.3 lakh (hilly areas) to build or upgrade a pucca house.',
    eligibility: 'Rural households without a pucca house, as listed under SECC and verified by the Gram Panchayat.',
    documents: ['Aadhaar card', 'Job card / household listing proof', 'Bank account details'],
    process: 'Verification against SECC lists; apply via the Block office; sanctioned amount released in instalments linked to construction progress.',
    link: 'https://pmayg.nic.in',
    min_age: 18, max_age: null, occupations: ['any'], area: 'rural', max_income: null,
    keywords: ['house', 'housing', 'awas', 'rural', 'home', 'shelter'],
  },
  {
    slug: 'pm-awas-urban', name: 'PM Awas Yojana — Urban', dept: 'MAHUD',
    benefits: 'Central assistance of ₹1.5–2.5 lakh for affordable housing, or interest subsidy on home loans (CLSS).',
    eligibility: 'Urban households without a pucca house or living in kutcha houses; EWS/LIG/MIG income limits apply.',
    documents: ['Aadhaar card', 'Income proof', 'Urban residence proof', 'Bank account details'],
    process: 'Apply through the municipal council (MAHUD) or the PMAY-U portal; verification followed by sanction.',
    link: 'https://pmay-urban.gov.in',
    min_age: 18, max_age: null, occupations: ['any'], area: 'urban', max_income: 1800000,
    keywords: ['house', 'housing', 'awas', 'urban', 'home', 'flat'],
  },
  {
    slug: 'old-age-pension-scheme', name: 'Indira Gandhi Old Age Pension (NSAP)', dept: 'Social Welfare Department',
    benefits: '₹200/month (60–79 years) and ₹500/month (80+) central assistance, topped up by the state.',
    eligibility: 'Citizens aged 60+ from BPL households.',
    documents: ['Age proof (Aadhaar)', 'BPL card or income certificate', 'Bank account details'],
    process: 'Apply at the DSWO office; field verification; pension credited monthly.',
    link: null,
    min_age: 60, max_age: null, occupations: ['senior_citizen', 'any'], area: 'any', max_income: null,
    keywords: ['pension', 'old age', 'senior', 'elderly'],
  },
  {
    slug: 'widow-pension-scheme', name: 'Indira Gandhi Widow Pension (NSAP)', dept: 'Social Welfare Department',
    benefits: '₹300/month central assistance plus state top-up for eligible widows.',
    eligibility: 'Widows aged 18+ from BPL households who have not remarried.',
    documents: ['Husband\'s death certificate', 'Aadhaar card', 'BPL/income certificate', 'Bank account details'],
    process: 'Apply at the DSWO office with documents; verification; monthly DBT.',
    link: null,
    min_age: 18, max_age: null, occupations: ['any'], area: 'any', max_income: null,
    keywords: ['pension', 'widow'],
  },
  {
    slug: 'pm-ujjwala', name: 'PM Ujjwala Yojana (Free LPG Connection)', dept: 'Food & Civil Supplies / Oil Companies',
    benefits: 'Free LPG gas connection plus first refill and stove assistance to women from poor households.',
    eligibility: 'Adult women from BPL/SECC-listed households without an existing LPG connection.',
    documents: ['Aadhaar card', 'Ration card', 'Bank account details', 'Self-declaration of no existing LPG connection'],
    process: 'Apply at the nearest LPG distributor or on the PMUY portal with KYC documents.',
    link: 'https://pmuy.gov.in',
    min_age: 18, max_age: null, occupations: ['homemaker', 'any'], area: 'any', max_income: null,
    keywords: ['gas', 'lpg', 'ujjwala', 'cooking', 'cylinder', 'woman'],
  },
  {
    slug: 'kcc-farmers', name: 'Kisan Credit Card — Crop Loan', dept: 'Agriculture Department / Banks',
    benefits: 'Crop loans up to ₹3 lakh at subsidised interest (effective ~4% after prompt-repayment incentive).',
    eligibility: 'Farmers, tenant farmers, sharecroppers and allied-activity workers (dairy, fishery).',
    documents: ['Land documents / tenancy proof', 'Aadhaar card', 'Crop plan', 'Photo'],
    process: 'Apply at any bank branch or CSC; bank verifies land and crop plan; KCC issued with credit limit.',
    link: null,
    min_age: 18, max_age: null, occupations: ['farmer'], area: 'any', max_income: null,
    keywords: ['farmer', 'loan', 'credit', 'kcc', 'crop'],
  },
  {
    slug: 'mgnrega-employment', name: 'MGNREGA — 100 Days Guaranteed Work', dept: 'Rural Development (via DC Office)',
    benefits: 'Up to 100 days of guaranteed wage employment per rural household per year at notified daily wages.',
    eligibility: 'Adult members of rural households willing to do unskilled manual work.',
    documents: ['Aadhaar card', 'Residence proof', 'Bank/post account details'],
    process: 'Get a job card at the Gram Panchayat; demand work in writing; work allotted within 15 days.',
    link: 'https://nrega.nic.in',
    min_age: 18, max_age: null, occupations: ['unemployed', 'daily_wage', 'any'], area: 'rural', max_income: null,
    keywords: ['job', 'work', 'employment', 'nrega', 'rural', 'wages'],
  },
  {
    slug: 'pm-svanidhi', name: 'PM SVANidhi — Street Vendor Loan', dept: 'MAHUD / Ministry of Housing & Urban Affairs',
    benefits: 'Collateral-free working-capital loan starting at ₹10,000, with interest subsidy and cashback on digital payments.',
    eligibility: 'Street vendors with a certificate of vending or survey identification in urban areas.',
    documents: ['Aadhaar card', 'Certificate of vending / LOU', 'Bank account details'],
    process: 'Apply through the lending bank / MFI or the PM SVANidhi portal; vendor verification by the Urban Local Body; loan disbursed.',
    link: 'https://pmsvanidhi.mohua.gov.in',
    min_age: 18, max_age: null, occupations: ['street_vendor', 'business'], area: 'urban', max_income: null,
    keywords: ['vendor', 'loan', 'street', 'business', 'svanidhi'],
  },
  {
    slug: 'pmegp-business', name: 'PMEGP — Prime Minister\'s Employment Generation Programme', dept: 'KVIC / DIC Manipur',
    benefits: 'Margin-money subsidy of 15–35% on bank loans of ₹10 lakh (manufacturing) / ₹5 lakh (service) to start a micro-enterprise.',
    eligibility: 'Individuals above 18 years; only VIII-pass required for projects above ₹10 lakh; new enterprises only.',
    documents: ['Aadhaar card', 'Project report', 'Caste certificate (for special categories)', 'Bank account details'],
    process: 'Apply on the PMEGP portal; attend EDP training if shortlisted; bank appraisal; unit setup and margin money credited as subsidy.',
    link: 'https://www.kviconline.gov.in/pmegpeportal',
    min_age: 18, max_age: null, occupations: ['unemployed', 'business', 'any'], area: 'any', max_income: null,
    keywords: ['business', 'loan', 'subsidy', 'startup', 'enterprise', 'pmegp', 'self employment'],
  },
  {
    slug: 'phd-scholarship', name: 'Ishan Uday Scholarship (NE Students in Higher Education)', dept: 'Education (S) Department',
    benefits: '₹5,400–₹7,800 per month for undergraduate and postgraduate students of the North-Eastern region.',
    eligibility: 'First-degree/PG students from NE states (including Manipur) studying in recognised institutions; income limits apply.',
    documents: ['Domicile/residence certificate', 'Income certificate', 'Previous marksheets', 'Admission proof', 'Bank account details'],
    process: 'Apply on the National Scholarship Portal; institute and state verify; scholarship credited monthly.',
    link: 'https://scholarships.gov.in',
    min_age: 17, max_age: 30, occupations: ['student'], area: 'any', max_income: 600000,
    keywords: ['scholarship', 'student', 'north east', 'ishan uday', 'college', 'university', 'graduation'],
  },
];

export const CONTACTS = [
  { department: 'Deputy Commissioner (DC) Office', service: 'Certificates & Revenue matters', phone: '03852451043', email: 'dcimphalwest@gmail.com', website: 'https://imphalwest.nic.in', office: 'DC Complex, Lamphelpat', district: 'Imphal West', is_demo: 1 },
  { department: 'Deputy Commissioner (DC) Office', service: 'Certificates & Revenue matters', phone: '03852230657', email: 'dcimphaleast@gmail.com', website: 'https://imphaleast.nic.in', office: 'DC Office, Porompat', district: 'Imphal East', is_demo: 1 },
  { department: 'Deputy Commissioner (DC) Office', service: 'Certificates & Revenue matters', phone: '03847222420', email: 'dcthoubal@gmail.com', website: 'https://thoubal.nic.in', office: 'DC Office, Thoubal', district: 'Thoubal', is_demo: 1 },
  { department: 'Deputy Commissioner (DC) Office', service: 'Certificates & Revenue matters', phone: '03847222046', email: 'dcbishnupur@gmail.com', website: 'https://bishnupur.nic.in', office: 'DC Office, Bishnupur', district: 'Bishnupur', is_demo: 1 },
  { department: 'District Hospital', service: 'General healthcare & CMHT enrollment', phone: '03852231555', email: 'dhimphal@example.gov.in', website: null, office: 'District Hospital, Imphal', district: 'Imphal West', is_demo: 1 },
  { department: 'Regional Transport Office (RTO)', service: 'Driving licence & vehicle registration', phone: '03852448765', email: 'rtomanipur@example.gov.in', website: 'https://parivahan.gov.in', office: 'RTO Office, Imphal', district: 'Imphal West', is_demo: 1 },
  { department: 'Social Welfare Department (DSWO)', service: 'Pensions & welfare schemes', phone: '03852451028', email: 'dswoimphal@example.gov.in', website: null, office: 'DSWO Office, Imphal', district: 'Imphal West', is_demo: 1 },
  { department: 'Agriculture Department', service: 'PM-KISAN, KCC & farming support', phone: '03852446526', email: 'agrimanipur@example.gov.in', website: 'https://manipuragri.nic.in', office: 'Directorate of Agriculture, Sanjenthong', district: 'Imphal West', is_demo: 1 },
  { department: 'PHED Manipur', service: 'Water supply connections & complaints', phone: '03852451045', email: 'phedmanipur@example.gov.in', website: 'https://phedmanipur.nic.in', office: 'PHED Complex, Porompat', district: 'Imphal East', is_demo: 1 },
  { department: 'MSPDCL (Electricity)', service: 'Streetlight & power complaints', phone: '03852451031', email: 'mspdcl@example.gov.in', website: null, office: 'MSPDCL Office, Keishampat', district: 'Imphal West', is_demo: 1 },
  { department: 'Manipur Police Control Room', service: 'Emergency police assistance', phone: '112', email: null, website: null, office: 'Control Room, Imphal', district: 'All Districts', is_demo: 0 },
  { department: 'Emergency Ambulance', service: 'Medical emergencies', phone: '108', email: null, website: null, office: 'Statewide', district: 'All Districts', is_demo: 0 },
  { department: 'Women Helpline', service: 'Support for women in distress', phone: '181', email: null, website: null, office: 'Statewide', district: 'All Districts', is_demo: 0 },
  { department: 'Child Helpline', service: 'Support for children in distress', phone: '1098', email: null, website: null, office: 'Statewide', district: 'All Districts', is_demo: 0 },
];
